[package]
name = "deplo"
version = "0.1.0"
authors = ["Takehiro Iyatomi <iyatomi@gmail.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
envsubst = "0.2.0"