# common settings
[common]
project_name = "deplo"

[common.release_targets]
nightly = { type = "Branch", path = "main" }
lab = { type = "Branch", path = "lab" }
prod = { type = "Tag", path = "[0-9]*" }


# version control system account settings
[vcs]
type = "Github"
email = "${SUNTOMI_VCS_ACCOUNT_EMAIL}"
account = "${SUNTOMI_VCS_ACCOUNT}"
key = "${SUNTOMI_VCS_ACCOUNT_KEY}"


# ci account setting, default should always be set
[ci.accounts.default]
type = "GhAction"
account = "${SUNTOMI_VCS_ACCOUNT}"
key = "${SUNTOMI_VCS_ACCOUNT_KEY}"


# workflow settings (CI)
[ci.workflow.integrate.base]
patterns = ["tools/docker/Dockerfile.base"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "docker:20.10", shell = "sh" } }
command = """
docker build -t ghcr.io/suntomi/deplo:base -f tools/docker/Dockerfile.base tools/docker
"""

[ci.workflow.integrate.builder]
patterns = ["tools/docker/Dockerfile.builder", "Cargo.*"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "docker:20.10", shell = "sh" } }
command = """
sh tools/scripts/copy_manifests.sh
docker build -t ghcr.io/suntomi/deplo:builder -f tools/docker/Dockerfile.builder tools/docker
"""

[ci.workflow.integrate.src]
patterns = [".*/src/.*", "Cargo.*"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "ghcr.io/suntomi/deplo:builder" } }
command = "cargo build"
[ci.workflow.integrate.src.caches.cargo]
keys = ["integrate-build-${{ runner.os }}-v1-${{ github.sha }}", "integrate-build-${{ runner.os }}-v1-"]
paths = ["target", "~/.cargo"]


# workflow settings (CD)
[ci.workflow.deploy.base]
patterns = ["tools/docker/Dockerfile.base"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "docker:20.10", shell = "sh" } }
command = """
docker build -t ghcr.io/suntomi/deplo:base -f tools/docker/Dockerfile.base tools/docker
echo ${SUNTOMI_VCS_ACCOUNT_KEY} | docker login ghcr.io -u ${SUNTOMI_VCS_ACCOUNT} --password-stdin
docker push ghcr.io/suntomi/deplo:base
"""

[ci.workflow.deploy.builder]
patterns = ["tools/docker/Dockerfile.builder", "Cargo.*"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "docker:20.10", shell = "sh" } }
command = """
sh tools/scripts/copy_manifests.sh
docker build -t ghcr.io/suntomi/deplo:builder -f tools/docker/Dockerfile.builder tools/docker
echo ${SUNTOMI_VCS_ACCOUNT_KEY} | docker login ghcr.io -u ${SUNTOMI_VCS_ACCOUNT} --password-stdin
docker push ghcr.io/suntomi/deplo:builder
"""

[ci.workflow.deploy.product]
depends = ["builder"]
patterns = [".*/src/.*", "Cargo.*"]
runner = { type = "Machine", os = "Linux", local_fallback = { image = "docker:20.10", shell = "sh" } }
command = """
set -e
mkdir -p tools/docker/bin
source tools/scripts/setup_release_env.sh
docker run --rm -v $(pwd):/workdir -w /workdir -e DEPLO_RELEASE_VERSION=${DEPLO_RELEASE_VERSION} \
    ghcr.io/suntomi/deplo:builder \
    bash -c "cargo build --release --target=x86_64-unknown-linux-musl && \
        cp /tmp/target/x86_64-unknown-linux-musl/release/cli /workdir/tools/docker/bin"
docker build -t ghcr.io/suntomi/deplo:${DEPLO_RELEASE_VERSION} -f tools/docker/Dockerfile tools/docker
echo ${SUNTOMI_VCS_ACCOUNT_KEY} | docker login ghcr.io -u ${SUNTOMI_VCS_ACCOUNT} --password-stdin
docker push ghcr.io/suntomi/deplo:${DEPLO_RELEASE_VERSION}
deplo vcs release ${DEPLO_RELEASE_TAG} -o name=${DEPLO_RELEASE_NAME}
deplo vcs release-assets ${DEPLO_RELEASE_TAG} /workdir/tools/docker/bin/cli --replace -o name=deplo-Linux
"""

[ci.workflow.deploy.mac]
depends = ["product"]
patterns = [".*/src/.*", "Cargo.*"]
runner = { type = "Machine", os = "MacOS" }
command = """
source tools/scripts/setup_release_env.sh
cargo build --release
deplo vcs release-assets ${DEPLO_RELEASE_TAG} target/release/cli --replace -o name=deplo-Darwin
"""
[ci.workflow.deploy.mac.caches.cargo]
keys = ["deploy-build-${{ runner.os }}-v1-${{ github.sha }}", "deploy-build-${{ runner.os }}-v1-"]
paths = ["target", "~/.cargo"]

[ci.workflow.deploy.win]
depends = ["product"]
patterns = [".*/src/.*", "Cargo.*"]
runner = { type = "Machine", os = "Windows" }
command = """
echo "source tools/scripts/setup_release_env.sh"
echo "cargo build --release"
echo "deplo vcs release-assets ${DEPLO_RELEASE_TAG} target/release/cli --replace -o name=deplo-Windows.exe"
"""
[ci.workflow.deploy.win.caches.cargo]
keys = ["deploy-build-${{ runner.os }}-v1-${{ github.sha }}", "deploy-build-${{ runner.os }}-v1-"]
paths = ["target", "~/.cargo"]
