#!/bin/bash

if [ "${DEPLO_CI_RELEASE_TARGET}" = "prod" ]; then
    export DEPLO_RELEASE_TAG=${DEPLO_CI_TAG_NAME}
    export DEPLO_RELEASE_NAME=${DEPLO_CI_TAG_NAME}
    export DEPLO_RELEASE_VERSION=${DEPLO_CI_TAG_NAME}
else
    export DEPLO_RELEASE_TAG=${DEPLO_CI_RELEASE_TARGET}
    export DEPLO_RELEASE_NAME=${DEPLO_CI_RELEASE_TARGET}
    export DEPLO_RELEASE_VERSION=${DEPLO_CI_RELEASE_TARGET}
fi
