version: 2.1

executors:
  deplo-main:
    working_directory: /workdir
    docker:
      - image: suntomi/deplo:latest
  deplo-osx:
    working_directory: ~/workdir
    macos:
      xcode: "12.1.0"

commands:
  fetch_repo:
    steps:
      - restore_cache:
          keys:
            - deplo-git-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - deplo-git-v1-{{ arch }}-{{ .Branch }}-
            - deplo-git-v1-{{ arch }}-
      - checkout
      - run:
          name: 'pull files in git LFS'
          command: |
            GIT_SSH_COMMAND='ssh -i /.ssh/id_rsa -o UserKnownHostsFile=/.ssh/known_hosts' \
              git lfs pull && git lfs checkout
      - run:
          name: 'maintain git'
          command: git gc
      - save_cache:
          key: deplo-git-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

workflows:
  version: 2
  deplo-main:
    jobs:
      - deplo-main
  deplo-osx:
    when:
      and:
        - equal: [true, << pipeline.parameters.osx >>]
        - not: 
          equal: ["", << pipeline.parameters.command >>]
    jobs:
      - deplo-osx:
          command: << pipeline.parameters.command >>
            
jobs:
  deplo-main:
    executor: deplo-main
    steps:
      - fetch_repo
      - run:
          name: start deplo
          command: deplo ci kick
  deplo-osx:
    executor: deplo-osx
    parameters:
      command:
        type: string
    steps:
      - fetch_repo
      - run:
          name: 'running deplo task'
          command: << parameters.command >>
