executors:
  deplo:
    working_directory: /workdir
    docker:
      - image: suntomi/deplo:6be550f77b13c0650d54d38b4345e1037b29f35a

commands:
  fetch_repo:
    steps:
      - restore_cache:
          keys:
            - deplo-git-v1-{ arch }-{ .Branch }-{ .Revision }
            - deplo-git-v1-{ arch }-{ .Branch }-
            - deplo-git-v1-{ arch }-
      - checkout
      - run:
          name: 'pull files in git LFS'
          command: |
            GIT_SSH_COMMAND='ssh -i /.ssh/id_rsa -o UserKnownHostsFile=/.ssh/known_hosts' \
              git lfs pull && git lfs checkout
      - run:
          name: 'maintain git'
          command: git gc
      - save_cache:
          key: deplo-git-v1-{ arch }-{ .Branch }-{ .Revision }
          paths:
            - ".git"
  load_deplo_tools:
    steps:
      - restore_cache:
        keys:
          - deplo-tools-v1-{ arch }-{ .Branch }-{ .Revision }
          - deplo-tools-v1-{ arch }-{ .Branch }-
          - deplo-tools-v1-{ arch }-
  save_deplo_tools:
    steps:
    - save_cache:
        key: deplo-tools-v1-{ arch }-{ .Branch }-{ .Revision }
        paths:
          - "/deplo-tools"

jobs:
  main:
    executor: deplo
    steps:
      - fetch_repo
      - load_deplo_tools
      - run:
        name: 'running CI jobs'
        command: deplo -w test/projects/dev ci
      - save_deplo_tools
