version: 2.1

workflows:
  version: 2
  deplo:
    jobs:
      - deplo

executors:
  deplo:
    working_directory: /workdir
    docker:
      - image: suntomi/deplo:4e6c4925dcd63aec082d781c03ee719de9963e3a

commands:
  fetch_repo:
    steps:
      - restore_cache:
          keys:
            - deplo-git-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - deplo-git-v1-{{ arch }}-{{ .Branch }}-
            - deplo-git-v1-{{ arch }}-
      - checkout
      - run:
          name: 'pull files in git LFS'
          command: |
            GIT_SSH_COMMAND='ssh -i /.ssh/id_rsa -o UserKnownHostsFile=/.ssh/known_hosts' \
              git lfs pull && git lfs checkout
      - run:
          name: 'maintain git'
          command: git gc
      - save_cache:
          key: deplo-git-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  load_deplo_tools:
    steps:
      - restore_cache:
          keys:
            - deplo-tools-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - deplo-tools-v1-{{ arch }}-{{ .Branch }}-
            - deplo-tools-v1-{{ arch }}-
  save_deplo_tools:
    steps:
    - save_cache:
        key: deplo-tools-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
        paths:
          - "/deplo-tools"

jobs:
  deplo:
    executor: deplo
    environment:
      DEPLO_CI_TYPE: Circle
    steps:
      - fetch_repo
      - load_deplo_tools
      - run:
          name: 'running CI jobs'
          command: /deplo -vvv -w test/projects/dev ci
      - save_deplo_tools