name: Deplo CI/CD

on: 
  push:
    branches: [lab,main]
    tags: [[0-9]*]
  pull_request:
    branches: [lab,main]
  workflow_dispatch:
    inputs:
      deplo_job_name:
        description: The name of the job to run
        requred: true
env:
  DEPLO_CI_PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
  DEPLO_CI_RUN_JOB_NAME: ${{ github.event.inputs.deplo_job_name }}
  SUNTOMI_VCS_ACCOUNT: ${{ secrets.SUNTOMI_VCS_ACCOUNT }}
  SUNTOMI_VCS_ACCOUNT_EMAIL: ${{ secrets.SUNTOMI_VCS_ACCOUNT_EMAIL }}
  SUNTOMI_VCS_ACCOUNT_KEY: ${{ secrets.SUNTOMI_VCS_ACCOUNT_KEY }}
jobs:
  deplo-main:
    name: Start CI
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:nightly
    outputs:
      DEPLO_OUTPUT_CLI_VERSION: ${{ steps.deplo-ci-kick.outputs.DEPLO_OUTPUT_CLI_VERSION }}
      deploy-base: ${{ steps.deplo-ci-kick.outputs.deploy-base }}
      deploy-builder: ${{ steps.deplo-ci-kick.outputs.deploy-builder }}
      deploy-mac: ${{ steps.deplo-ci-kick.outputs.deploy-mac }}
      deploy-product: ${{ steps.deplo-ci-kick.outputs.deploy-product }}
      deploy-win: ${{ steps.deplo-ci-kick.outputs.deploy-win }}
      integrate-base: ${{ steps.deplo-ci-kick.outputs.integrate-base }}
      integrate-builder: ${{ steps.deplo-ci-kick.outputs.integrate-builder }}
      integrate-src: ${{ steps.deplo-ci-kick.outputs.integrate-src }}
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Start deplo
        id: deplo-ci-kick
        run: deplo ci kick
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: false
  deplo-finish:
    name: Cleanup CI
    if: ${{ !failure() }}
    needs: ["deplo-main","deploy-base","deploy-builder","deploy-mac","deploy-product","deploy-win","integrate-base","integrate-builder","integrate-src"]
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:nightly
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cleanup deplo
        id: deplo-ci-fin
        run: deplo ci fin
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: false
  deploy-base:
    needs: [deplo-main]
    if: ${{ needs.deplo-main.outputs.deploy-base && !failure() }}
    name: Running job deploy-base
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
  
      - name: deploy base
        run: deplo ci deploy base
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-builder:
    needs: [deplo-main]
    if: ${{ needs.deplo-main.outputs.deploy-builder && !failure() }}
    name: Running job deploy-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
  
      - name: deploy builder
        run: deplo ci deploy builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-mac:
    needs: ["deploy-product","deplo-main"]
    if: ${{ needs.deplo-main.outputs.deploy-mac && !failure() }}
    name: Running job deploy-mac
    runs-on: macos-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Darwin -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cache cargo
        id: deplo-cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo
          key: deploy-build-${{ runner.os }}-v1-${{ github.sha }}
          restore-keys:
            deploy-build-${{ runner.os }}-v1-
      - name: Mark cache result
        if: steps.deplo-cache-cargo.outputs.cache-hit == 'true'
        run: echo "DEPLO_CACHE_CARGO_HIT=true" >> $GITHUB_ENV
      - name: deploy mac
        run: |
          source tools/scripts/setup_release_env.sh
          cargo build --release
          deplo vcs release-assets ${DEPLO_RELEASE_TAG} target/release/cli --replace -o name=deplo-Darwin
          
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-product:
    needs: ["deploy-builder","deplo-main"]
    if: ${{ needs.deplo-main.outputs.deploy-product && !failure() }}
    name: Running job deploy-product
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
  
      - name: deploy product
        run: deplo ci deploy product
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-win:
    needs: ["deploy-product","deplo-main"]
    if: ${{ needs.deplo-main.outputs.deploy-win && !failure() }}
    name: Running job deploy-win
    runs-on: windows-latest
  
    steps:
  
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cache cargo
        id: deplo-cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo
          key: deploy-build-${{ runner.os }}-v1-${{ github.sha }}
          restore-keys:
            deploy-build-${{ runner.os }}-v1-
      - name: Mark cache result
        if: steps.deplo-cache-cargo.outputs.cache-hit == 'true'
        run: echo "DEPLO_CACHE_CARGO_HIT=true" >> $GITHUB_ENV
      - name: deploy win
        run: |
          source tools/scripts/setup_release_env.sh
          cargo build --release
          deplo vcs release-assets ${DEPLO_RELEASE_TAG} target/release/cli --replace -o name=deplo-Windows.exe
          
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-base:
    needs: [deplo-main]
    if: ${{ needs.deplo-main.outputs.integrate-base && !failure() }}
    name: Running job integrate-base
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
  
      - name: integrate base
        run: deplo ci integrate base
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-builder:
    needs: [deplo-main]
    if: ${{ needs.deplo-main.outputs.integrate-builder && !failure() }}
    name: Running job integrate-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
  
      - name: integrate builder
        run: deplo ci integrate builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-src:
    needs: [deplo-main]
    if: ${{ needs.deplo-main.outputs.integrate-src && !failure() }}
    name: Running job integrate-src
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        run: curl -L https://github.com/suntomi/deplo/releases/download/nightly/deplo-Linux -o /usr/local/bin/deplo
      - name: Change cli permission
        run: chmod +x /usr/local/bin/deplo
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cache cargo
        id: deplo-cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo
          key: integrate-build-${{ runner.os }}-v1-${{ github.sha }}
          restore-keys:
            integrate-build-${{ runner.os }}-v1-
      - name: Mark cache result
        if: steps.deplo-cache-cargo.outputs.cache-hit == 'true'
        run: echo "DEPLO_CACHE_CARGO_HIT=true" >> $GITHUB_ENV
      - name: integrate src
        run: deplo ci integrate src
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true