name: Deplo Launcher

on: 
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  deplo:
    name: running CI jobs
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: suntomi/deplo:c27be81c06c93e5efe753c6ce60f3008a6d35e1b
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run Deplo
        env:
          DEPLO_CI_TYPE: GhAction
          DEPLO_GHACTION_PULL_REQUEST_URL: ${{ github.event.pull_request.comments_url }}
        run: /deplo -vvv -w test/projects/dev ci kick
