name: Deplo CI/CD

on: 
  push:
    branches: [main,release]
  pull_request:
    branches: [main,release]
  workflow_dispatch:
    inputs:
      deplo_job_name:
        description: The name of the job to run
        requred: true
env:
  DEPLO_CI_PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
  DEPLO_CI_RUN_JOB_NAME: ${{ github.event.inputs.deplo_job_name }}
  SUNTOMI_VCS_ACCOUNT: ${{ secrets.SUNTOMI_VCS_ACCOUNT }}
  SUNTOMI_VCS_ACCOUNT_EMAIL: ${{ secrets.SUNTOMI_VCS_ACCOUNT_EMAIL }}
  SUNTOMI_VCS_ACCOUNT_KEY: ${{ secrets.SUNTOMI_VCS_ACCOUNT_KEY }}
jobs:
  deplo-main:
    name: Start CI
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:18c59aee8836cf033308444e7c3f329e0ea3eed4
    outputs:
      DEPLO_OUTPUT_CLI_GIT_HASH: ${{ steps.deplo-ci-kick.DEPLO_OUTPUT_CLI_GIT_HASH }}
      deploy-base: ${ steps.deplo-ci-kick.deploy-base }
      deploy-builder: ${ steps.deplo-ci-kick.deploy-builder }
      deploy-mac: ${ steps.deplo-ci-kick.deploy-mac }
      deploy-product: ${ steps.deplo-ci-kick.deploy-product }
      deploy-win: ${ steps.deplo-ci-kick.deploy-win }
      integrate-base: ${ steps.deplo-ci-kick.integrate-base }
      integrate-builder: ${ steps.deplo-ci-kick.integrate-builder }
      integrate-src: ${ steps.deplo-ci-kick.integrate-src }
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Start deplo
        id: deplo-ci-kick
        run: deplo ci kick
      - name: Cache deplo cli
        id: cache-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ steps.deplo-ci-kick.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: false
  deplo-finish:
    name: Cleanup CI
    needs: ["deplo-main","deploy-base","deploy-builder","deploy-mac","deploy-product","deploy-win","integrate-base","integrate-builder","integrate-src"]
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:18c59aee8836cf033308444e7c3f329e0ea3eed4
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cleanup deplo
        id: deplo-ci-fin
        run: deplo ci fin
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: false
  deploy-base:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-base
    name: Running job deploy-base
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: deploy base
        run: deplo ci deploy base
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-builder:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-builder
    name: Running job deploy-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: deploy builder
        run: deplo ci deploy builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-mac:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-mac
    name: Running job deploy-mac
    runs-on: windows-latest
  
    steps:
  
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: deploy mac
        run: deplo ci deploy mac
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-product:
    needs: ["deploy-mac","deploy-win","deploy-builder","deplo-main"]
    if: needs.deplo-main.outputs.deploy-product
    name: Running job deploy-product
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: deploy product
        run: deplo ci deploy product
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  deploy-win:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-win
    name: Running job deploy-win
    runs-on: macos-latest
  
    steps:
  
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: deploy win
        run: deplo ci deploy win
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-base:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.integrate-base
    name: Running job integrate-base
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: integrate base
        run: deplo ci integrate base
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-builder:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.integrate-builder
    name: Running job integrate-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: integrate builder
        run: deplo ci integrate builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: true
  integrate-src:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.integrate-src
    name: Running job integrate-src
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - name: Fetch deplo cli
        id: fetch-deplo-cli
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/deplo
          key: deplo-cli-v1-${{ needs.deplo-main.outputs.DEPLO_OUTPUT_CLI_GIT_HASH }}
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: integrate src
        run: deplo ci integrate src
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@a3d459813f3429bd95fc48bcd980b2fb40f10ad0
        with:
          sudo: false