name: Deplo CI/CD

on: 
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  deplo:
    name: running CI jobs
    runs-on: ubuntu-latest
    container: suntomi/deplo:b71a1248a1b53f23d905f7d75be944de36366989
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run Deplo
        env:
          DEPLO_GHACTION_PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
          DEPLO_ORG_NAME: ${{ secrets.DEPLO_ORG_NAME }}
          DEPLO_APP_NAME: ${{ secrets.DEPLO_APP_NAME }}
          DEPLO_APP_ID: ${{ secrets.DEPLO_APP_ID }}
          DEPLO_CLOUD_ACCESS_KEY: ${{ secrets.DEPLO_CLOUD_ACCESS_KEY }}
          DEPLO_VCS_ACCESS_EMAIL: ${{ secrets.DEPLO_VCS_ACCESS_EMAIL }}
          DEPLO_VCS_ACCESS_KEY: ${{ secrets.DEPLO_VCS_ACCESS_KEY }}
          DEPLO_CI_ACCESS_KEY: ${{ secrets.DEPLO_CI_ACCESS_KEY }}
          DEPLO_CLIENT_APP_ID: ${{ secrets.DEPLO_CLIENT_APP_ID }}
          DEPLO_BUILD_UNITY_SERIAL_CODE: ${{ secrets.DEPLO_BUILD_UNITY_SERIAL_CODE }}
          DEPLO_BUILD_UNITY_ACCOUNT_EMAIL: ${{ secrets.DEPLO_BUILD_UNITY_ACCOUNT_EMAIL }}
          DEPLO_BUILD_UNITY_ACCOUNT_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ACCOUNT_PASSWORD }}
          DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PASSWORD }}
          DEPLO_BUILD_UNITY_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYALIAS_PASSWORD }}
          DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_NAME: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_NAME }}
          DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PATH: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PATH }}
          DEPLO_BUILD_UNITY_IOS_TEAM_ID: ${{ secrets.DEPLO_BUILD_UNITY_IOS_TEAM_ID }}
          DEPLO_BUILD_UNITY_IOS_P12_SIGNING_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_IOS_P12_SIGNING_PASSWORD }}
          DEPLO_BUILD_UNITY_IOS_SIGNING_FILES_PATH: ${{ secrets.DEPLO_BUILD_UNITY_IOS_SIGNING_FILES_PATH }}
          DEPLO_DISTRIBUTION_APPLE_ACCOUNT: ${{ secrets.DEPLO_DISTRIBUTION_APPLE_ACCOUNT }}
          DEPLO_DISTRIBUTION_APPLE_PASSWORD: ${{ secrets.DEPLO_DISTRIBUTION_APPLE_PASSWORD }}
          DEPLO_DISTRIBUTION_GOOGLE_ACCESS_KEY: ${{ secrets.DEPLO_DISTRIBUTION_GOOGLE_ACCESS_KEY }}

        run: git --no-pager log -5 && deplo -vvv -w test/projects/dev ci kick
