name: Deplo Launcher

on: 
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  deplo:
    name: running CI jobs
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: suntomi/deplo:157f61edae54ef69c9bb5a80c663d3e28caa32fe
    steps:
      - uses: actions/checkout@v2
        lfs: true
      - name: Run Deplo
        env:
          DEPLO_GHACTION_PULL_REQUEST_URL: ${ github.event.pull_request.comments_url }
        run: deplo -w test/projects/dev ci
