name: Deplo Launcher

on: 
  push:
    branches: [master,release]
  pull_request:
    branches: [master,release]

jobs:
  deplo:
    name: running CI jobs
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: suntomi/deplo:e3dbb2622f31c9fa30cee3a97eaac3719851d9a7
    steps:
      - uses: actions/checkout@v2
        lfs: true
      - name: Run Deplo
        env:
          DEPLO_CI_TYPE: GhAction
          DEPLO_GHACTION_PULL_REQUEST_URL: ${{ github.event.pull_request.comments_url }}
        run: deplo -w test/projects/dev ci
