name: Deplo Task on OSX

on: 
  workflow_dispatch:
    inputs:
      command:
        description: 'command to execute'
        required: true

env:
  DEPLO_GHACTION_PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
  DEPLO_ORG_NAME: ${{ secrets.DEPLO_ORG_NAME }}
  DEPLO_APP_NAME: ${{ secrets.DEPLO_APP_NAME }}
  DEPLO_APP_ID: ${{ secrets.DEPLO_APP_ID }}
  DEPLO_CLOUD_ACCESS_KEY: ${{ secrets.DEPLO_CLOUD_ACCESS_KEY }}
  DEPLO_VCS_ACCESS_EMAIL: ${{ secrets.DEPLO_VCS_ACCESS_EMAIL }}
  DEPLO_VCS_ACCESS_KEY: ${{ secrets.DEPLO_VCS_ACCESS_KEY }}
  DEPLO_CI_ACCESS_KEY: ${{ secrets.DEPLO_CI_ACCESS_KEY }}
  DEPLO_CLIENT_APP_ID: ${{ secrets.DEPLO_CLIENT_APP_ID }}
  DEPLO_BUILD_UNITY_SERIAL_CODE: ${{ secrets.DEPLO_BUILD_UNITY_SERIAL_CODE }}
  DEPLO_BUILD_UNITY_ACCOUNT_EMAIL: ${{ secrets.DEPLO_BUILD_UNITY_ACCOUNT_EMAIL }}
  DEPLO_BUILD_UNITY_ACCOUNT_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ACCOUNT_PASSWORD }}
  DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PASSWORD }}
  DEPLO_BUILD_UNITY_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYALIAS_PASSWORD }}
  DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_NAME: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_NAME }}
  DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PATH: ${{ secrets.DEPLO_BUILD_UNITY_ANDROID_KEYSTORE_PATH }}
  DEPLO_BUILD_UNITY_IOS_TEAM_ID: ${{ secrets.DEPLO_BUILD_UNITY_IOS_TEAM_ID }}
  DEPLO_BUILD_UNITY_IOS_P12_SIGNING_PASSWORD: ${{ secrets.DEPLO_BUILD_UNITY_IOS_P12_SIGNING_PASSWORD }}
  DEPLO_BUILD_UNITY_IOS_SIGNING_FILES_PATH: ${{ secrets.DEPLO_BUILD_UNITY_IOS_SIGNING_FILES_PATH }}
  DEPLO_DISTRIBUTION_APPLE_ACCOUNT: ${{ secrets.DEPLO_DISTRIBUTION_APPLE_ACCOUNT }}
  DEPLO_DISTRIBUTION_APPLE_PASSWORD: ${{ secrets.DEPLO_DISTRIBUTION_APPLE_PASSWORD }}
  DEPLO_DISTRIBUTION_GOOGLE_ACCESS_KEY: ${{ secrets.DEPLO_DISTRIBUTION_GOOGLE_ACCESS_KEY }}

jobs:
  deplo:
    name: Running CI jobs
    runs-on: macos-10.15
    container: suntomi/deplo:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      - name: Generate cache key
        run: echo "DEPLO_TOOL_CACHE_KEY=$(deplo -w test/projects/dev info version -o json | jq -jr .toolset)" >> $GITHUB_ENV
      - name: Cache runtime dependencies
        uses: actions/cache@v2
        with:
          path: /Applications/DeploTools
          key: deplo-tools-v1-${{ runner.os }}-${{ env.DEPLO_TOOL_CACHE_KEY }}
      - name: Run comand
        run: bash -c "$(echo \"${ toJSON(github.event.client_payload) }\" | jq -jr .command)"
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
