name: Deplo CI/CD

on: 
  push:
    branches: [main,release]
  pull_request:
    branches: [main,release]
  workflow_dispatch:
    inputs:
      deplo_job_name:
        description: The name of the job to run
        requred: true
env:
  DEPLO_CI_PULL_REQUEST_URL: ${{ github.event.pull_request.url }}
  DEPLO_CI_RUN_JOB_NAME: ${{ github.event.inputs.deplo_job_name }}
  SUNTOMI_VCS_ACCOUNT: ${{ secrets.SUNTOMI_VCS_ACCOUNT }}
  SUNTOMI_VCS_ACCOUNT_EMAIL: ${{ secrets.SUNTOMI_VCS_ACCOUNT_EMAIL }}
  SUNTOMI_VCS_ACCOUNT_KEY: ${{ secrets.SUNTOMI_VCS_ACCOUNT_KEY }}
jobs:
  deplo-main:
    name: Start CI
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:043f57b50710c6632b2fafd4832c1679c97d255d
    outputs:
      deploy-builder: steps.deplo-ci-kick.deploy-builder
      deploy-mac: steps.deplo-ci-kick.deploy-mac
      deploy-product: steps.deplo-ci-kick.deploy-product
      deploy-win: steps.deplo-ci-kick.deploy-win
      integrate-builder: steps.deplo-ci-kick.integrate-builder
      integrate-src: steps.deplo-ci-kick.integrate-src
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Start deplo
        id: deplo-ci-kick
        run: deplo ci kick
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: false
  deplo-finish:
    name: Cleanup CI
    needs: [deplo-main]
    runs-on: ubuntu-latest
    container: ghcr.io/suntomi/deplo:043f57b50710c6632b2fafd4832c1679c97d255d
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Cleanup deplo
        id: deplo-ci-fin
        run: deplo ci fin
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: false
  deploy-builder:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-builder
    name: Running job deploy-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job deploy-builder
        run: deplo ci run deploy-builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: true
  deploy-mac:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-mac
    name: Running job deploy-mac
    runs-on: windows-latest
  
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job deploy-mac
        run: deplo ci run deploy-mac
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: true
  deploy-product:
    needs: ["deploy-mac","deploy-win","deploy-builder","deplo-main"]
    if: needs.deplo-main.outputs.deploy-product
    name: Running job deploy-product
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job deploy-product
        run: deplo ci run deploy-product
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: true
  deploy-win:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.deploy-win
    name: Running job deploy-win
    runs-on: macos-latest
  
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job deploy-win
        run: deplo ci run deploy-win
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: true
  integrate-builder:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.integrate-builder
    name: Running job integrate-builder
    runs-on: ubuntu-latest
  
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job integrate-builder
        run: deplo ci run integrate-builder
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: true
  integrate-src:
    needs: [deplo-main]
    if: needs.deplo-main.outputs.integrate-src
    name: Running job integrate-src
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ github.sha }}
          restore-keys:
            deplo-git-v1-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Run job integrate-src
        run: deplo ci run integrate-src
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: umegaya/action-tmate@132a4fe73c61b3459556a7c1baf1eefc8c3e15d2
        with:
          sudo: false