name: Deplo Launcher

on: 
  push:
    branches: [release,master]
  pull_request:
    branches: [release,master]

jobs:
  deplo:
    name: running CI jobs
    # This job runs on Linux
    runs-on: ubuntu-latest
    container: suntomi/deplo:ff8deef89f26453cc456d4a2cfaaa18a75025dd6
    steps:
      - uses: actions/checkout@v2
        lfs: true
      - name: Run Deplo
        env:
          DEPLO_GHACTION_PULL_REQUEST_URL: ${ github.event.pull_request.comments_url }
        run: deplo -w test/projects/dev ci
